spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qingzhou
    username: root
    password: sun12345
#    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

http:
  port: 8898

server:
  port: 8899
  tomcat:
    uri-encoding: UTF-8
  servlet:
    encoding:
      charset: UTF-8
  ssl:
    enabled: true
    key-store-password: ks9xt7rl7z
    key-store-type: JKS
    key-store: classpath:navergo.icu.jks
mybatis:
  #标注待解析的mapper的xml文件位置
  mapper-locations: classpath:mapper/*.xml
  #标注实体类位置
  type-aliases-package: icu.navergo.demo.entity
  configuration:
    #开启mybatis驼峰式命名规则自动转换
    map-underscore-to-camel-case: true
jedis:
  time: 60