spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: sun12345
#    driver-class-name: com.mysql.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
server:
  port: 8899